import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const manifestPath = join(root, 'package.json');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
const sourceFiles = Array.isArray(manifest.pluginSrc) ? manifest.pluginSrc : [];

if (!sourceFiles.length) {
	throw new Error('package.json pluginSrc must list plugin source files in execution order.');
}

const chunks = await Promise.all(
	sourceFiles.map(async (file) => {
		const source = await readFile(join(root, file), 'utf8');
		return `// ${file}\n${source.trim()}\n`;
	})
);

const outputPath = join(root, manifest.bundle || 'dist/plugin.js');
const output = [
	'// Generated by scripts/build-plugin.mjs. Do not edit directly.',
	'"use strict";',
	...chunks
].join('\n\n') + '\n';

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, output);
console.log(`Wrote ${outputPath.replace(`${root}/`, '')}`);
